# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- .jekyll-cache
- vendor # https://github.com/jekyll/jekyll/issues/5267#issuecomment-241379902

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
#jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
# jekyll-seo-tag > Owners twitter username
author: ADCL # jekyll-seo-tag > default author
# social: # jekyll-seo-tag > social overrides
  # name: ADCL # jekyll-seo-tag > real name
  # links:  # jekyll-seo-tag > social aliases (sameAs)
    # - https://twitter.com/DavidDarnes
    # - https://www.facebook.com/daviddarnes
    # - https://www.linkedin.com/in/daviddarnes
    # - https://github.com/daviddarnes
# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
  # options: ["SMART", "FOOTNOTES"]
  # extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
timezone: America/Denver # Timezone for blog posts and alike

# 5. Collections
collections:
  index:
    output: true
  about:
    output: true
  people:
    output: true
  projects:
    output: true
  publications:
    output: true

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-US # Set the site language
title: "Autonomous Decision and Control Lab" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logos/ADCL-rounded.svg" # Site logo, also used in jekyll-seo-tag
description: "Autonomous Decision and Control Lab" # Site description and default description, also used in jekyll-seo-tag
url: "https://www.cu-adcl.org/" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/CU-ADCL/CU-ADCL.github.io"
repository: "CU-ADCL/CU-ADCL.github.io"
email: "zachary.sunberg@colorado.edu"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
# date_format: "%-d %B %Y" # Blog post date formatting using placeholder formatting
# google_analytics: ""
# google_analytics_anonymize_ip: ""
# service_worker: false # Will turn off the service worker if set to false
# short_name: "Al" # The web application short name, defaults to the site title
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: "/assets/logos/ADCL-square.svg"
  32: "/assets/logos/ADCL-square.svg"
  96: "/assets/logos/ADCL-square.svg"
  120: "/assets/logos/ADCL-square.svg"
  144: "/assets/logos/ADCL-square.svg"
  180: "/assets/logos/ADCL-square.svg"
  512: "/assets/logos/ADCL-square.svg"
  1024: "/assets/logos/ADCL-square.svg"

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
